name: py37
dependencies:
- python=3.7

- pip:
  - requests>=2.9.1
  - sphinx==1.7.4
  - sphinx-autobuild==0.7.1
  - git+https://github.com/python/python-docs-theme.git#egg=python-docs-theme
  - git+https://github.com/pypa/pypa-docs-theme.git#egg=pypa-docs-theme